accounts/urls.py
# urls.py
from django.urls import path
from .views import *
app_name = 'accounts'
from .views import employee_dashboard, employer_dashboard

urlpatterns = [
    path('employee_registration/', employee_registration, name='employee_registration'),
    path('employer_registration/', employer_registration, name='employer_registration'),
    path('employee_dashboard/', employee_dashboard, name='employee_dashboard'),
    path('employer_dashboard/', employer_dashboard, name='employer_dashboard'),
    path('user_login/', user_login, name='user_login'),  # Add this line
    path('logout/', logout_view, name='logout'),
    path('edit_employee/', edit_employee, name='edit_employee'),
    path('edit_employee_popup/', edit_employee_popup, name='edit_employee_popup'),
    path('accounts/employee_dashboard/', employee_dashboard, name='employee_dashboard'),
    path('jobs/dashboard/', employer_dashboard, name='employer_dashboard'),
    # Add other paths for your views as needed
]

job_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from jobs.views import home
from jobs.views import dashboard
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('dashboard/', dashboard, name='dashboard'),
    path('jobs/', include('jobs.urls', namespace='jobs')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('mtn_payment_app/', include('mtn_payment_app.urls', namespace='mtn_payment_app')),
]

from django.contrib.staticfiles.urls import staticfiles_urlpatterns # new
urlpatterns += staticfiles_urlpatterns()

jobs/urls.py
from django.urls import path
from .views import *

app_name = 'jobs'

urlpatterns = [
    path('contact/', contact, name='contact'),
    path('about/', about_us, name='about'),
    path('service/', service, name='service'),
    path('job-post/', job_post, name='job-post'),
    path('job-listing/', job_listing, name='job-listing'),
    path('job-single/<int:id>/', job_single, name='job-single'),
    path('search/', SearchView.as_view(), name='search'),
    path('apply/<int:job_listing_id>/', job_apply, name='apply'),
    path('dashboard/', dashboard, name='dashboard'),
    path('thank-you/', thank_you_page, name='thank_you'),
    path('drafted_jobs/', drafted_jobs, name='drafted_jobs'),
    path('job-draft/<int:id>/', job_draft, name='job-draft'),  # New URL pattern for job draft
]

handler404 = 'jobs.views.error_404_view'
handler500 = 'jobs.views.error_500_view'

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_employee = models.BooleanField(default=True)
    skills = models.TextField(blank=True)
    schedule = models.CharField(max_length=255, blank=True)
    can_volunteer = models.BooleanField(default=False)
    contact_number = models.CharField(max_length=20, blank=True)
    address = models.TextField(blank=True)
    job_preferences = models.CharField(max_length=255, blank=True)
    is_part_time = models.BooleanField(default=False)
    is_full_time = models.BooleanField(default=False)
    is_contract = models.BooleanField(default=False)

    def __str__(self):
        return self.user.get_full_name()

    def get_latest_information(self):
        # Return the latest information for the employee
        return {
            'skills': self.skills,
            'schedule': self.schedule,
            'can_volunteer': self.can_volunteer,
            'contact_number': self.contact_number,
            'address': self.address,
            'job_preferences': self.job_preferences,
            'is_part_time': self.is_part_time,
            'is_full_time': self.is_full_time,
            'is_contract': self.is_contract,
        }

class EmployeeUpdates(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    update_date = models.DateTimeField(auto_now_add=True)
    update_fields = models.TextField()  # Store updated fields and values as JSON

class TimeClock(models.Model):
    employee = models.OneToOneField(Employee, on_delete=models.CASCADE)
    punch_in = models.DateTimeField(blank=True, null=True)
    punch_out = models.DateTimeField(blank=True, null=True)

class Attendance(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    attendance_date = models.DateField()
    hours_worked = models.DecimalField(max_digits=5, decimal_places=2)

class LeaveRequest(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    leave_start_date = models.DateField()
    leave_end_date = models.DateField()
    reason = models.TextField()

class RecentAttendance(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    recent_attendance_date = models.DateField()
    hours_worked = models.DecimalField(max_digits=5, decimal_places=2)

class LeaveHistory(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    leave_start_date = models.DateField()
    leave_end_date = models.DateField()
    reason = models.TextField()

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Employee

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        ]

    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs['placeholder'] = 'Enter a valid e-mail'
        self.fields['username'].widget.attrs['placeholder'] = 'Enter a username'

class EmployeeRegistrationForm(UserRegistrationForm):
    username = forms.CharField(max_length=10)

    class Meta(UserRegistrationForm.Meta):
        fields = UserRegistrationForm.Meta.fields + ['username']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_employee = True  # Set the is_employee attribute
        if commit:
            user.save()
        return user

class EmployeeRegistrationForm(UserRegistrationForm):
    username = forms.CharField(max_length=10)

    class Meta(UserRegistrationForm.Meta):
        fields = UserRegistrationForm.Meta.fields + ['username']

class EmployerRegistrationForm(UserRegistrationForm):
    company_name = forms.CharField(max_length=100)

    class Meta(UserRegistrationForm.Meta):
        fields = UserRegistrationForm.Meta.fields + ['company_name']

class UserLoginForm(forms.Form):
    username = forms.CharField(label='Username')
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Username'

class EmployeeProfileForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['skills', 'schedule', 'can_volunteer', 'contact_number', 'address', 'job_preferences', 'is_part_time', 'is_full_time', 'is_contract']

accounts/views.py
# views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from .forms import EmployeeRegistrationForm, EmployerRegistrationForm, UserLoginForm
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.conf import settings
from .models import Employee
from .forms import EmployeeProfileForm
from jobs.models import JobListing  # Update this import statement
from jobs.models import UserProfile 
from jobs.models import ApplyJob
from jobs.models import User# Update this import statement
from django.shortcuts import render
from jobs.models import JobListing, ApplyJob
from django.contrib.auth import login
from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from .forms import EmployeeRegistrationForm  # Import your EmployeeRegistrationForm
from django.contrib.auth.models import User

@login_required
def employee_dashboard(request):
    try:
        # Try to get the associated Employee object for the logged-in user
        employee = request.user.employee
    except Employee.DoesNotExist:
        # If the Employee object doesn't exist, redirect to the registration page
        return redirect('accounts:employee_registration')

    context = {'employee': employee}
    return render(request, 'accounts/employee_dashboard.html', context)


def employee_registration(request):
    if request.method == 'POST':
        form = EmployeeRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()

            # Create an Employee object for the user
            Employee.objects.create(user=user)

            # Send confirmation email
            subject = 'Employee Registration Confirmation'
            message = (
                f'Thank you, {user.first_name} {user.last_name}, for registering as an employee on JOBNET360.\n\n'
                f'We appreciate your commitment to being part of our community. '
                f'Please find below some important information:\n\n'
                f'Login: jobnet360.com\n'
                f'Email: {user.email}\n\n'
                f'You can now log in to your account and explore our platform. If you have any '
                f'questions or need assistance, feel free to contact us at edigitalnetwork842@gmail.com.\n\n'
                f'We look forward to your contributions and success on JOBNET360!\n\n'
                f'Best regards,\n'
                f'Abraham Bedell \n CEO @ JOBNET360'
            )
            from_email = 'joannabedella@gmail.com'  # Change to your email address
            to_email = [user.email]
            send_mail(subject, message, from_email, to_email, fail_silently=False)

            login(request, user)
            return redirect('accounts:employee_dashboard')  # Redirect to the employee dashboard
    else:
        form = EmployeeRegistrationForm()

    context = {'form': form}
    return render(request, 'accounts/employee_registration.html', context)




def employer_registration(request):
    if request.method == 'POST':
        form = EmployerRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()

            # Send confirmation email with user's name
            subject = 'Welcome to Career Hub - Employer Registration Confirmation'
            message = (
    f'Thank you, {user.first_name} {user.last_name}, for registering as an employer on JOBNET360.\n\n'
    f'We appreciate your commitment to being part of our community. '
    f'Please find below some important information:\n\n'
    f'Login: jobnet360.com\n'
    f'Email: {user.email}\n\n'
    f'You can now log in to your account and explore our platform. If you have any '
    f'questions or need assistance, feel free to contact us at edigitalnetwork842@gmail.com.\n\n'
    f'We look forward to your contributions and success on JOBNET360!\n\n'
    f'Best regards,\n'
    f'Abraham Bedell \n CEO @ JOBNET360'
)

            from_email = 'joannabedella@gmail.com'  # Change to your email address
            to_email = [user.email]
            send_mail(subject, message, from_email, to_email, fail_silently=False)

            login(request, user)
            return redirect('jobs:dashboard')  # Redirect to the employer dashboard
    else:
        form = EmployerRegistrationForm()

    context = {'form': form}
    return render(request, "accounts/employer_registration.html", context)

@login_required
def edit_employee(request):
    employee = request.user.employee  # Assuming user has a related employee instance

    if request.method == 'POST':
        form = EmployeeProfileForm(request.POST, request.FILES, instance=employee)
        if form.is_valid():
            form.save()
            return redirect('accounts:employee_dashboard')  # Correct URL or view name
    else:
        form = EmployeeProfileForm(instance=employee)

    context = {'form': form}
    return render(request, 'accounts/employee_dashboard.html', context)

@login_required
def edit_employee_popup(request):
    # Add logic to fetch the employee instance
    employee = request.user.employee  # Assuming user has a related employee instance

    # Assuming you have a form for editing employee information
    if request.method == 'POST':
        form = EmployeeProfileForm(request.POST, instance=employee)
        if form.is_valid():
            form.save()
            return redirect('accounts:employee_dashboard')  # Correct URL or view name
    else:
        form = EmployeeProfileForm(instance=employee)

    context = {'form': form}
    return render(request, 'accounts/edit_employee_popup.html', context)


  


from django.contrib import messages

def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            user = authenticate(username=username, password=password)

            if user is not None and user.is_active:
                is_employee = getattr(user, 'is_employee', False)

                if is_employee:
                    # Handle employee login
                    login(request, user)
                    return redirect('accounts:employee_dashboard')
                else:
                    # Handle other user login (employer, superuser, etc.)
                    login(request, user)
                    return redirect('jobs:dashboard')
            else:
                messages.error(request, 'Invalid login credentials. Please try again.')
    else:
        form = UserLoginForm()

    context = {'form': form}
    return render(request, "accounts/user_login.html", context)



def logout_view(request):
    logout(request)
    return redirect('accounts:user_login')


@login_required
def employer_dashboard(request):
    # Retrieve statistics and other data needed for the dashboard
    total_applied_jobs = ApplyJob.objects.count()
    total_users = User.objects.count()
    total_jobs = JobListing.objects.count()

    # Retrieve unique companies with jobs
    companies_with_jobs = JobListing.objects.values('company_name').distinct().count()

    # Retrieve employee information for the employee list
    employee_list = Employee.objects.all()  # Update this query based on your model

    context = {
        'total_applied_jobs': total_applied_jobs,
        'total_users': total_users,
        'total_jobs': total_jobs,
        'companies_with_jobs': companies_with_jobs,
        'employee_list': employee_list,
    }

    # Use the correct app name in the render function
    return render(request, 'jobs/dashboard.html', context)

templates/accounts/edit_employee_popup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
{% include 'navbar.html' %}
    <section class="site-section" id="next-section">
        <div class="container">
            <div class="col-lg-6 mb-5 mb-lg-0">
               
            </div>
            <div class="row">
                <form method="post" action="{% url 'accounts:edit_employee' %}">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-primary btn-md text-white">Save Changes</button>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

templates/accounts/employee_dashboard.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% include 'navbar.html' %}
<head>
    <!-- Add these links to include Bootstrap and jQuery -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.0.8/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
  </head>
  
    <div class="container mt-4">
        <h1 style="text-align: center;">Welcome <br> {{ user.first_name }} {{ user.last_name }}</h1>

        <div class="row">
            <div class="col-md-12">
                <div class="card bg-light mb-3">
                    <div class="card-header">Employee Information</div>
                    <div class="card-body">
                        <p class="card-text">
                            <strong>Skills:</strong> {{ employee.skills }}<br>
                            <strong>Schedule:</strong> {{ employee.schedule }}<br>
                            <strong>Contact Number:</strong> {{ employee.contact_number }}<br>
                            <strong>Address:</strong> {{ employee.address }}<br>
                            <strong>Job Preferences:</strong> {{ employee.job_preferences }}<br>
                            <strong>Part-Time:</strong> {% if employee.is_part_time %}Yes{% else %}No{% endif %}<br>
                            <strong>Full-Time:</strong> {% if employee.is_full_time %}Yes{% else %}No{% endif %}<br>
                            <strong>Contract:</strong> {% if employee.is_contract %}Yes{% else %}No{% endif %}
                        </p>
                    </div>
                </div>
            </div>
        </div>
<a href="{% url 'accounts:edit_employee_popup' %}" class="btn btn-primary">
    <span class=" pe-2">
        <i class="bi bi-pencil"></i>
    </span>
    Edit Info</a>


{% endblock %}
edit_employee_popup

templates/accounts/employer_dashboard.html
{% load static %}
{% include 'navbar.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        .side-menu {
            background-color: #212529;
            padding: 20px;
            height: 100vh;
        }

        .side-menu ul li {
            margin-bottom: 10px;
        }

        .side-menu ul li a {
            color: #f8f9fa;
            text-decoration: none;
        }

        .side-menu ul li a:hover {
            color: #f8f9fa;
            text-decoration: underline;
        }

        .content {
            margin-left: 220px;
            padding: 20px;
        }

        .card {
            background-color: #ffffff;
            padding: 20px;
            margin-bottom: 20px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }

        .icon-case {
            width: 60px;
            height: 60px;
            background-color: #f8f9fa;
            margin-left: 15px;
            position: relative;
        }

        .icon-case img {
            width: 40px;
            height: 40px;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
        }

        .employee-list,
        .new-students {
            background-color: #ffffff;
            padding: 20px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            margin-bottom: 20px;
        }

        .employee-list table,
        .new-students table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        .employee-list table tr td,
        .new-students table tr td {
            padding: 10px;
            border: 1px solid #dee2e6;
        }

        .employee-list table tr td img {
            width: 30px;
            height: 30px;
        }

        .title {
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .title h2 {
            margin: 0;
        }

        .title a.btn {
            text-decoration: none;
            color: #007bff;
        }

        .title a.btn:hover {
            text-decoration: underline;
        }

    </style>
</head>

<body>
    <div class="side-menu">
        <div class="brand-name">
            <h1>JOBNET-360</h1>
        </div>
        <ul>
            <li><img src="{% static 'dashboard (2).png' %}" alt="">&nbsp; <span><a href="{% url 'home' %}">HOME</a></span> </li>
            <li><img src="{% static 'help-web-button.png' %}" alt="">&nbsp;<span><a href="{% url 'jobs:job-listing' %}">JOB_LIST</a></span> </li>
            <li>
            <img src="{% static 'logout-icon.png' %}" alt="">&nbsp;<span><a href="{% url 'accounts:user_login' %}">Logout</a></span></li> 
        </ul>
    </div>
    <div class="container">
        <div class="header">
            <div class="nav">
                <div class="search">
                    <input type="text" placeholder="Search..">
                    <button type="submit"><img src="{% static 'search.png' %}" alt=""></button>
                </div>
                <div class="user">
                    <a href="#" class="btn">{{ user.username }}</a>
                    <img src="{% static 'notifications.png' %}" alt="">
                    <div class="img-case">
                    
                    </div>
                </div>
            </div>
        </div>
        <div class="content">
            <div class="cards">
                <div class="content">
                    <div class="cards">
                        <div class="card">
                            <div class="box">
                                <i class="fas fa-briefcase"></i>
                                <h1>13</h1>
                                <h3>Total Company:</h3>
                            </div>
                            <div class="icon-case"></div>
                        </div>
                        <div class="card">
                            <div class="box">
                                <i class="fas fa-users"></i>
                                <h1>{{ total_users }}</h1>
                                <h3>Total Users on Platform</h3>
                            </div>
                            <div class="icon-case"></div>
                        </div>
                        <div class="card">
                            <div class="box">
                                <i class="fas fa-briefcase"></i>
                                <h1>{{ total_jobs }}</h1>
                                <h3>Total Jobs: </h3>
                            </div>
                            <div class="icon-case"></div>
                        </div>
                    </div>
               
            </div>

            <!-- Employee List section -->
            <div class="employee-list">
                <div class="title">
                    <h2>Employee List</h2>
                    <a href="#" class="btn">View All</a>
                </div>
                <table class="table table-bordered">
                    <thead class="thead-dark">
                        <tr>
                            <th>Employee Name</th>
                            <th>Contact Number</th>
                            <th>Email</th>
                            <th>Skills</th>
                            <th>Schedule</th>
                            <th>Can Volunteer</th>
                            <th>Address</th>
                            <th>Job Preferences</th>
                            <th>Part-Time</th>
                            <th>Full-Time</th>
                            <th>Contract</th>
                            <!-- Add more columns as needed -->
                        </tr>
                    </thead>
                    <tbody>
                        {% for employee in employee_list %}
                            <tr>
                                <td>{{ employee.user.get_full_name }}</td>
                                <td>{{ employee.contact_number }}</td>
                                <td>{{ employee.user.email }}</td>
                                <td>{{ employee.skills }}</td>
                                <td>{{ employee.schedule }}</td>
                                <td>{% if employee.can_volunteer %}Yes{% else %}No{% endif %}</td>
                                <td>{{ employee.address }}</td>
                                <td>{{ employee.job_preferences }}</td>
                                <td>{% if employee.is_part_time %}Yes{% else %}No{% endif %}</td>
                                <td>{% if employee.is_full_time %}Yes{% else %}No{% endif %}</td>
                                <td>{% if employee.is_contract %}Yes{% else %}No{% endif %}</td>
                                <!-- Add more columns as needed -->
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <!-- Companies with Jobs Posted section -->
            <div class="new-students">
                <div class="title">
                    <h2>Companies with Jobs Posted</h2>
                    <a href="#" class="btn">View All</a>
                </div>
                <table class="table table-bordered">
                    <thead class="thead-dark">
                        <tr>
                            <th>Logo</th>
                            <th>Company Name</th>
                            <th>More Info</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for company in companies_with_jobs %}
                            <tr>
                                <td><img src="{% static 'user.png' %}" alt=""></td>
                                <td>{{ company }}</td>
                                <td><img src="{% static 'info.png' %}" alt=""></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</body>

</html>

templates/accounts/employer_registration.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% load static %}

{% block content %}
    <!-- Hero Section -->
    <section class="home-section section-hero inner-page overlay bg-image"
             style="background-image: url('https://res.cloudinary.com/dj6izkhrs/image/upload/v1704655253/zq0ij1ajgzy5jmjgirsy.jpg');" id="home-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-12">
                    <div class="mb-5 text-center">
                        <h2 class="text-white font-weight-bold">Not registered yet?</h2>
                        <p>If you have any questions, please feel free to contact us, our customer service center is working for you 24/7.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Sign Up Section -->
    <section class="site-section" id="next-section">
        <div class="container">
            <div class="col-lg-6 mb-5 mb-lg-0">
                <center><h1 class="lead">Sign Up</h1></center>
            </div>
            <div class="row">
                <form method="post" action="{% url 'accounts:employer_registration' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-primary btn-md text-white">Register as Employer</button>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

templates/accounts/user_login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<section class="home-section section-hero inner-page overlay bg-image"
style="background-image: url('https://res.cloudinary.com/dj6izkhrs/image/upload/v1704655253/zq0ij1ajgzy5jmjgirsy.jpg');" id="home-section">
<div class="container">
<div class="row align-items-center justify-content-center">
   <div class="col-md-12">
       <div class="mb-5 text-center">
           <h2 class="text-white font-weight-bold">LOGIN</h2>
       </div>
   </div>
</div>
</div>
</section>
<!-- Login Section -->
<section class="site-section" id="next-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5 mb-5 mb-lg-0">
                <p>Already have your account?</p>
                <form action="{% url 'accounts:user_login' %}" method="POST">
                    {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                    {% endfor %}
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="row form-group">
                        <div class="col-md-12">
                            <input type="submit" value="Login" class="btn btn-primary btn-md text-white">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
<!-- Call to Action Section -->
<section class="py-5 bg-image overlay-primary fixed overlay">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-8">
                <h2 class="text-white">Looking For Opportunities?</h2>
                <p class="mb-0 text-white lead">Explore a world of possibilities and discover exciting career opportunities that match your skills and aspirations.</p>
                
            </div>
            <div class="col-md-3 ml-auto">
                <a href="{% url 'accounts:employee_registration' %}" class="btn btn-warning btn-block btn-lg">Register as Employee</a>
                <a href="{% url 'accounts:employer_registration' %}" class="btn btn-info btn-block btn-lg">Register as Employer</a>
            </div>
        </div>
    </div>
</section>


{% endblock %}