accounts/urls.py
# urls.py
from django.urls import path
from .views import *
app_name = 'accounts'
from .views import employee_dashboard, employer_dashboard

urlpatterns = [
    path('employee_registration/', employee_registration, name='employee_registration'),
    path('employer_registration/', employer_registration, name='employer_registration'),
    path('employee_dashboard/', employee_dashboard, name='employee_dashboard'),
    path('employer_dashboard/', employer_dashboard, name='employer_dashboard'),
    path('user_login/', user_login, name='user_login'),  # Add this line
    path('logout/', logout_view, name='logout'),
    path('edit_employee/', edit_employee, name='edit_employee'),
    path('edit_employee_popup/', edit_employee_popup, name='edit_employee_popup'),
    path('accounts/employee_dashboard/', employee_dashboard, name='employee_dashboard'),
    path('jobs/dashboard/', employer_dashboard, name='employer_dashboard'),
    # Add other paths for your views as needed
]

job_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from jobs.views import home
from jobs.views import dashboard
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('dashboard/', dashboard, name='dashboard'),
    path('jobs/', include('jobs.urls', namespace='jobs')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('mtn_payment_app/', include('mtn_payment_app.urls', namespace='mtn_payment_app')),
]

from django.contrib.staticfiles.urls import staticfiles_urlpatterns # new
urlpatterns += staticfiles_urlpatterns()

jobs/urls.py
from django.urls import path
from .views import *

app_name = 'jobs'

urlpatterns = [
    path('contact/', contact, name='contact'),
    path('about/', about_us, name='about'),
    path('service/', service, name='service'),
    path('job-post/', job_post, name='job-post'),
    path('job-listing/', job_listing, name='job-listing'),
    path('job-single/<int:id>/', job_single, name='job-single'),
    path('search/', SearchView.as_view(), name='search'),
    path('apply/<int:job_listing_id>/', job_apply, name='apply'),
    path('dashboard/', dashboard, name='dashboard'),
    path('thank-you/', thank_you_page, name='thank_you'),
    path('drafted_jobs/', drafted_jobs, name='drafted_jobs'),
    path('job-draft/<int:id>/', job_draft, name='job-draft'),  # New URL pattern for job draft
]

handler404 = 'jobs.views.error_404_view'
handler500 = 'jobs.views.error_500_view'

templates/base.html
{% load static %}


<html lang="en">
<head>
    <title>Careers </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/custom-bs.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-select.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/line-icons/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- Favicon -->
<link href="{% static 'img/favicon.ico' %}" rel="icon">

<!-- Google Web Fonts -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@700;800&display=swap" rel="stylesheet">

<!-- Icon Font Stylesheet -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

<!-- Libraries Stylesheet -->
<link href="{% static 'assets/lib/animate/animate.min.css' %}" rel="stylesheet">
<link href="{% static 'assets/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
<!-- Add Bootstrap JS library -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


<!-- Customized Bootstrap Stylesheet -->
<link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">

<!-- Template Stylesheet -->
<link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

    {% block styles %}{% endblock %}


</head>
<body id="top">


<div class="site-wrap">

    <div class="site-mobile-menu site-navbar-target">
        <div class="site-mobile-menu-header">
            <div class="site-mobile-menu-close mt-3">
                <span class="icon-close2 js-menu-toggle"></span>
            </div>
        </div>
        <div class="site-mobile-menu-body"></div>
    </div> <!-- .site-mobile-menu -->
    {% load crispy_forms_tags %}


    

    {% block content %}

    {% endblock %}




            <!-- Testimonial End -->
        

        <!-- Footer Start -->
        <div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
            <div class="container py-5">
                <div class="row g-5">
                    <div class="col-lg-3 col-md-6">
                        <h5 class="text-white mb-4">JOBNET-360 </h5>
                        <a class="btn btn-link text-white-50" href="">About Us</a>
                        <a class="btn btn-link text-white-50" href="">Contact Us</a>
                        <a class="btn btn-link text-white-50" href="">Our Services</a>
                        <a class="btn btn-link text-white-50" href="">Privacy Policy</a>
                        <a class="btn btn-link text-white-50" href="">Terms & Condition</a>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h5 class="text-white mb-4">Quick Links</h5>
                        <a class="btn btn-link text-white-50" href="">About Us</a>
                        <a class="btn btn-link text-white-50" href="">Contact Us</a>
                        <a class="btn btn-link text-white-50" href="">Our Services</a>
                        <a class="btn btn-link text-white-50" href="">Privacy Policy</a>
                        <a class="btn btn-link text-white-50" href="">Terms & Condition</a>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h5 class="text-white mb-4">Contact</h5>
                        <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>Barnersville, Town Hall Community</p>
                        <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+231 778187295</p>
                        <p class="mb-2"><i class="fa fa-envelope me-3"></i>edigitalnetwork842@gmail.com</p>
                        <div class="d-flex pt-2">
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h5 class="text-white mb-4">Newsletter</h5>
                        <p></p>
                        <div class="position-relative mx-auto" style="max-width: 400px;">
                            <input class="form-control bg-transparent w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                            <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="copyright">
                    <div class="row">
                        <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                            &copy; <a class="border-bottom" href="#">JOBNET-360</a>, All Right Reserved. 
							
							<!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
							Designed By <a class="border-bottom" href="edigitalnetwork.tech">E-Digital Network</a>
                        </div>
                        <div class="col-md-6 text-center text-md-end">
                            <div class="footer-menu">
                                <a href="">Home</a>
                                <a href="">Cookies</a>
                                <a href="">Help</a>
                                <a href="">FQAs</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->


        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'assets/lib/wow/wow.min.js' %}"></script>
<script src="{% static 'assets/lib/easing/easing.min.js' %}"></script>
<script src="{% static 'assets/lib/waypoints/waypoints.min.js' %}"></script>
<script src="{% static 'assets/lib/owlcarousel/owl.carousel.min.js' %}"></script>

<!-- Template Javascript -->
<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}


{% block content %}

{% include 'navbar.html' %}

  <!-- HOME -->
  <section class="home-section section-hero overlay bg-image"  style="background-image: url('https://res.cloudinary.com/dj6izkhrs/image/upload/v1704646775/r87c3azrzlmvl5r9nt9i.jpg');" id="home-section">

    <div class="container">
      <div class="row align-items-center justify-content-center">
        <div class="col-md-12">
          <div class="mb-5 text-center">
            <h1 class="text-white font-weight-bold">Welcome to JOBNET-360 </h1>
            <p>Empowering Careers, Transforming Futures </p>
          </div>
          <form id="job-main-form" method="get" action="{% url 'jobs:search' %}" class="search-jobs-form">
            <div class="row mb-5">
              <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
                 <input type="text"  id="title" name="title" class="form-control form-control-lg" placeholder=" Software Engineer ... ">
              </div>
              <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
                 <input    type="text" id="job_location" name="job_location" class="form-control form-control-lg" placeholder="Monrovia, Liberia">
              </div>
              <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
                <select id="employment_status" name="employment_status" class="form-control">
                  <option>Part Time</option>
                  <option>Full Time</option>
                  <option>Freelance</option>
                </select>
              </div>


              <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
                <button type="submit" class="btn btn-primary btn-lg btn-block text-white btn-search"><span class="icon-search icon mr-2"></span>Search Job</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>


  </section>
            <!-- Category Start -->
            <div class="container-xxl py-5">
              <div class="container">
                  <h1 class="text-center mb-5 wow fadeInUp" data-wow-delay="0.1s">Explore By Category</h1>
                  <div class="row g-4">
                    <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                        <a class="cat-item rounded p-4" href="">
                            <i class="fa fa-3x fa-mail-bulk text-primary mb-4"></i>
                            <h6 class="mb-3">Marketing</h6>
                            <ol>
                                <li>Marketing Manager</li>
                                <li>Digital Marketing Specialist</li>
                                <li>Content Creator</li>
                                <li>Social Media Coordinator</li>
                            </ol>
                        </a>
                    </div>
                    <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.3s">
                        <a class="cat-item rounded p-4" href="">
                            <i class="fa fa-3x fa-headset text-primary mb-4"></i>
                            <h6 class="mb-3">Customer Service</h6>
                            <ol>
                                <li>Customer Service Representative</li>
                                <li>Customer Support Specialist</li>
                                <li>Client Success Manager</li>
                                <li>Help Desk Technician</li>
                            </ol>
                        </a>
                    </div>
<!-- Human Resource -->
<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.5s">
    <a class="cat-item rounded p-4" href="">
        <i class="fa fa-3x fa-user-tie text-primary mb-4"></i>
        <h6 class="mb-3">Human Resource</h6>
        <ol>
            <li>Human Resources Generalist</li>
            <li>Recruitment Specialist</li>
            <li>HR Coordinator</li>
            <li>Employee Relations Manager</li>
        </ol>
    </a>
</div>

<!-- Project Management -->
<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.7s">
    <a class="cat-item rounded p-4" href="">
        <i class="fa fa-3x fa-tasks text-primary mb-4"></i>
        <h6 class="mb-3">Project Management</h6>
        <ol>
            <li>Project Manager</li>
            <li>Project Coordinator</li>
            <li>Scrum Master</li>
            <li>Program Manager</li>
        </ol>
    </a>
</div>

                      <!-- Business Development -->
<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
    <a class="cat-item rounded p-4" href="">
        <i class="fa fa-3x fa-chart-line text-primary mb-4"></i>
        <h6 class="mb-3">Business Development</h6>
        <ol>
            <li>Business Development Manager</li>
            <li>Sales Development Representative</li>
            <li>Partnership Manager</li>
            <li>Market Research Analyst</li>
        </ol>
    </a>
</div>

<!-- Sales & Communication -->
<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.3s">
    <a class="cat-item rounded p-4" href="">
        <i class="fa fa-3x fa-hands-helping text-primary mb-4"></i>
        <h6 class="mb-3">Sales & Communication</h6>
        <ol>
            <li>Sales Representative</li>
            <li>Account Executive</li>
            <li>Communication Specialist</li>
            <li>Public Relations Manager</li>
        </ol>
    </a>
</div>

<!-- Teaching & Education -->
<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.5s">
    <a class="cat-item rounded p-4" href="">
        <i class="fa fa-3x fa-book-reader text-primary mb-4"></i>
        <h6 class="mb-3">Teaching & Education</h6>
        <ol>
            <li>Teacher</li>
            <li>Education Consultant</li>
            <li>Instructional Designer</li>
            <li>Training Specialist</li>
        </ol>
    </a>
</div>

<!-- Design & Creative -->
<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.7s">
    <a class="cat-item rounded p-4" href="">
        <i class="fa fa-3x fa-drafting-compass text-primary mb-4"></i>
        <h6 class="mb-3">Design & Creative</h6>
        <ol>
            <li>Graphic Designer</li>
            <li>UX/UI Designer</li>
            <li>Creative Director</li>
            <li>Multimedia Artist</li>
        </ol>
    </a>
</div>
<!-- Information Technology (IT) -->
<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
    <a class="cat-item rounded p-4" href="">
        <i class="fa fa-3x fa-laptop-code text-primary mb-4"></i>
        <h6 class="mb-3">Information Technology (IT)</h6>
        <ol>
            <li>IT Specialist</li>
            <li>Software Developer</li>
            <li>Network Engineer</li>
            <li>Systems Analyst</li>
        </ol>
    </a>
</div>

<!-- Finance & Accounting -->
<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.3s">
    <a class="cat-item rounded p-4" href="">
        <i class="fa fa-3x fa-chart-line text-primary mb-4"></i>
        <h6 class="mb-3">Finance & Accounting</h6>
        <ol>
            <li>Accountant</li>
            <li>Financial Analyst</li>
            <li>Auditor</li>
            <li>Tax Consultant</li>
        </ol>
    </a>
</div>

<!-- Healthcare & Medical -->
<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.5s">
    <a class="cat-item rounded p-4" href="">
        <i class="fa fa-3x fa-hospital text-primary mb-4"></i>
        <h6 class="mb-3">Healthcare & Medical</h6>
        <ol>
            <li>Registered Nurse</li>
            <li>Medical Laboratory Technologist</li>
            <li>Healthcare Administrator</li>
            <li>Physical Therapist</li>
        </ol>
    </a>
</div>
<!-- Real Estate & Property Management -->
<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.7s">
    <a class="cat-item rounded p-4" href="">
        <i class="fa fa-3x fa-home text-primary mb-4"></i>
        <h6 class="mb-3">Real Estate & Property Management</h6>
        <ol>
            <li>Real Estate Agent</li>
            <li>Property Manager</li>
            <li>Leasing Consultant</li>
            <li>Facilities Coordinator</li>
        </ol>
    </a>
</div>


                  </div>
              </div>
          </div>
          <!-- Category End -->
  



    <!-- Jobs Start -->
<div class="container-xxl py-5">
  <div class="container">
      <h1 class="text-center mb-5 wow fadeInUp" data-wow-delay="0.1s">Job Listing</h1>
      <div class="tab-class text-center wow fadeInUp" data-wow-delay="0.3s">
          <!-- Add the tabs and tab content here -->
      </div>
  
      <!-- Job items -->
      {% for job in query %}
      <div class="job-item p-4 mb-4">
          <div class="row g-4">
              <div class="col-sm-12 col-md-8 d-flex align-items-center">
                {% if job.image %}
                <img class="flex-shrink-0 img-fluid border rounded" src="{{ job.image.url }}" alt="Job Image" style="width: 80px; height: 80px;">
            {% else %}
                <!-- Show a default placeholder image if no image is available -->
                <img class="flex-shrink-0 img-fluid border rounded" src="{% static 'placeholder_image.jpg' %}" alt="Placeholder Image" style="width: 80px; height: 80px;">
            {% endif %}
                  <div class="text-start ps-4">
                      <h5 class="mb-3">{{ job.title }}</h5>
                      <span class="text-truncate me-3"><i class="fa fa-map-marker-alt text-primary me-2"></i>{{ job.job_location }}</span>
                      <span class="text-truncate me-3"><i class="far fa-clock text-primary me-2"></i>{{ job.employment_status }}</span>
                      <span class="text-truncate me-0"><i class="far fa-money-bill-alt text-primary me-2"></i>{{ job.Salary }}</span>
                  </div>
              </div>
              <div class="col-sm-12 col-md-4 d-flex flex-column align-items-start align-items-md-end justify-content-center">
                  <div class="d-flex mb-3">
                     
                      {% if user.is_authenticated %}
                      <a class="btn btn-light btn-square me-3" href=""><i class="far fa-heart text-primary"></i></a>
                      <a class="btn btn-primary" href="{% url 'jobs:job-single' job.id %}">Apply Now</a>
                      {% else %}
                      <a class="btn btn-light btn-square me-3" href=""><i class="far fa-heart text-primary"></i></a>
                      <a class="btn btn-primary" href="{% url 'accounts:user_login' %}">Apply Now</a>
                      {% endif %}
                  </div>
                  <small class="text-truncate"><i class="far fa-calendar-alt text-primary me-2"></i>Date Line: {{ job.application_deadline }}</small>
              </div>
          </div>
      </div>
      {% endfor %}


      <!-- Pagination 
      <div class="pagination">
          <span class="step-links">
              {% if query.has_previous %}
              <a href="?page=1">&laquo; first</a>
              <a href="?page={{ query.previous_page_number }}">previous</a>
              {% endif %}

              <span class="current">
                  Page {{ query.number }} of {{ query.paginator.num_pages }}.
              </span>

              {% if query.has_next %}
              <a href="?page={{ query.next_page_number }}">next</a>
              <a href="?page={{ query.paginator.num_pages }}">last &raquo;</a>
              {% endif %}
          </span>
      </div>-->
  </div>
</div>
{% endblock %}

templates/navbar.html
{% load static %}
     <!-- Add this variable in your Django template -->
     {% with is_user_authenticated=user.is_authenticated %}
     {% endwith %}
<!-- Navbar Start -->
<nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
  <!-- Navbar content... -->
  <a href="{% url 'home' %}" class="navbar-brand d-flex align-items-center text-center py-0 px-4 px-lg-5">
    <h1 class="m-0 text-primary">JOBNET-360</h1>
  </a>
  <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <div class="navbar-nav ms-auto p-4 p-lg-0">
      <a href="{% url 'home' %}" class="nav-item nav-link active">Home</a>
      <a href="{% url 'jobs:about' %}" class="nav-item nav-link">About</a>
      <a href="{% url 'accounts:user_login' %}" class="nav-item nav-link">SignIn</a>
      {% if user.is_authenticated %}
      <a href="{% url 'jobs:contact' %}" class="nav-item nav-link">Contact</a>
      {% endif %}
      <div class="nav-item dropdown">
        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Jobs</a>
        <div class="dropdown-menu rounded-0 m-0">
          {% if user.is_authenticated %}
          <a href="{% url 'accounts:logout' %}" class="dropdown-item">Logout</a>
          {% endif %}
          <a href="{% url 'jobs:job-listing' %}" class="dropdown-item">Job List</a>

        </div>
      </div>
      <div class="nav-item dropdown">
        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Dashboard</a>
        <div class="dropdown-menu rounded-0 m-0">
            {% if user.is_authenticated %}
            {% if user.is_employer or user.is_superuser %}
                    <a href="{% url 'jobs:dashboard' %}" class="dropdown-item">Employer Dashboard<i class="fa fa-arrow-right ms-3"></i></a>
                {% endif %}
                {% if user.employee.is_employee %}
                    <a href="{% url 'accounts:employee_dashboard' %}" class="dropdown-item">Employee Dashboard<i class="fa fa-arrow-right ms-3"></i></a>
                {% endif %}
            {% else %}
                <p class="dropdown-item">login to access the dashboard</p>
            {% endif %}
        </div>
    </div>
    
      
    </div>
  </div>
</nav>
<!-- Navbar End -->
<!--<header class="site-navbar mt-3">
  <div class="container-fluid">
    <div class="row align-items-center">
      <div class="site-logo col-6"><a href="{% url 'home' %}">Careers</a></div>

      <nav class="mx-auto site-navigation">
        <ul class="site-menu js-clone-nav d-none d-xl-block ml-0 pl-0">
          <li><a href="{% url 'home' %}" class="nav-link active">Home</a></li>
          <li><a href="{% url 'jobs:job-listing' %}">Job Listings</a></li>
          <li><a href="{% url 'jobs:about' %}">About</a></li>
          <li><a href="{% url 'jobs:contact' %}">Contact</a></li>
             <li><a href="{% url 'jobs:service' %}"> Services</a></li>


          <li class="d-lg-none"><a href="#">Contact Us</a></li>
        </ul>
      </nav>
{% if user.is_authenticated %}
      <div class="right-cta-menu text-right d-flex aligin-items-center col-6">
        <div class="ml-auto">


          <ul class="nav nav-tabs">

  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="True" aria-expanded="false">
      {{request.user.first_name}} {{request.user.last_name}}</a>
    <div class="dropdown-menu">
      <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>

    </div>
  </li>


</ul>




        </div>
      </div>



{% endif %}
    </div>
  </div>
    </header>
  -->

templates/thank_you.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Thank You</title>
	<link href='https://fonts.googleapis.com/css?family=Lato:300,400|Montserrat:700' rel='stylesheet' type='text/css'>
	<style>
		@import url(//cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css);
		@import url(//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css);
	</style>
	<link rel="stylesheet" href="https://2-22-4-dot-lead-pages.appspot.com/static/lp918/min/default_thank_you.css">
	<script src="https://2-22-4-dot-lead-pages.appspot.com/static/lp918/min/jquery-1.9.1.min.js"></script>
	<script src="https://2-22-4-dot-lead-pages.appspot.com/static/lp918/min/html5shiv.js"></script>
	<style>
		.return-link {
			display: inline-block;
			margin-top: 20px;
			text-decoration: none;
			color: #333;
		}
		.return-link i {
			margin-right: 5px;
		}
	</style>
</head>
<body>
	<header class="site-header" id="header">
		<h1 class="site-header__title" data-lead-id="site-header-title">THANK YOU!</h1>
	</header>

	<div class="main-content">
		<i class="fa fa-check main-content__checkmark" id="checkmark"></i>
		<p class="main-content__body" data-lead-id="main-content-body">Thank you for your application! Your details have been submitted successfully. We appreciate your interest in our company and will get back to you soon.</p>
		<a href="/dashboard" class="return-link"><i class="fa fa-arrow-left"></i> Back to Dashboard</a>
	</div>

	<footer class="site-footer" id="footer">
		<p class="site-footer__fineprint" id="fineprint">Copyright ©2024 | JOBNET-360 Rights Reserved</p>
	</footer>
</body>
</html>